// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWsLzCLF3DUWLcDZ9h7VEd1av9hf61pY',
    appId: '1:489578958167:web:1b67d0a3482d36a0768212',
    messagingSenderId: '489578958167',
    projectId: 'todolistapp-f9602',
    authDomain: 'todolistapp-f9602.firebaseapp.com',
    storageBucket: 'todolistapp-f9602.appspot.com',
    measurementId: 'G-JC0S0VFBG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoh2nmSOoITJqTmh6UvJFtsUAkTgx6wnQ',
    appId: '1:489578958167:android:86526dbacb3e42af768212',
    messagingSenderId: '489578958167',
    projectId: 'todolistapp-f9602',
    storageBucket: 'todolistapp-f9602.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeWsLzCLF3DUWLcDZ9h7VEd1av9hf61pY',
    appId: '1:489578958167:web:8dae6d4c86cca033768212',
    messagingSenderId: '489578958167',
    projectId: 'todolistapp-f9602',
    authDomain: 'todolistapp-f9602.firebaseapp.com',
    storageBucket: 'todolistapp-f9602.appspot.com',
    measurementId: 'G-X19EC2XXZY',
  );
}
